spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://postgres-products:5432/products
    username: products_username
    password: products_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8100

otel:
  service:
    name: products-service
  exporter:
    otlp:
      endpoint: "http://ht-otel-collector:4317"
  metric:
    export:
      interval: 15s
